spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/project-hear2speak-database
    username: postgres
    password: password

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
